
site_name:        StateSpaceReconstruction.jl
repo_url:         https://github.com/kahaaga/StateSpaceReconstruction.jl
site_description: State space reconstruction/embedding and partitioning tools.
site_author:      kahaaga

theme:
  name: 'material'

extra_css:
  - assets/documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js
  - assets/documenter.js
  - assets/search.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Overview: index.md
  - Embedding: embedding.md
  - Rectangular partitions:
    - Types of partitions: partition/binningtypes.md
    - Axis minima and step sizes: partition/minima_stepsizes.md
    - Coordinate representation: partition/coordinate_representation.md
    - Integer encoding representation: partition/integer_representation.md
    - Marginal visitation frequencies: partition/marginal_visitation_frequency.md
  - Simplex partitions:
    - Overview: simplexpartition/simplex.md
